import { IVerb } from "./models/IVerb"

export const verbsList: IVerb[] | any = [
    {id: 1, v1: "abide", v2: "abode / abided", v3: "abode", translate: "дотримуватися"},
    {id: 2, v1: "arise", v2: "arose", v3: "arisen", translate: "виникати"}, 
    {id: 3, v1: "awake", v2: "awoke / awakened", v3: "awoken / awakened", translate: "прокидатися"}, 

    {id: 4, v1: "backslide", v2: "backslid", v3: "backslid / backslidden", translate: "відступати"}, 
    {id: 5, v1: "be", v2: "was / were", v3: "been", translate: "бути"}, 
    {id: 6, v1: "bear", v2: "bore", v3: "born / borne", translate: "нести"}, 
    {id: 7, v1: "beat", v2: "beat", v3: "beaten", translate: "бити"}, 
    {id: 8, v1: "become", v2: "became", v3: "become", translate: "ставати"}, 
    {id: 9, v1: "begin", v2: "began", v3: "begun", translate: "починати"}, 
    {id: 10, v1: "bend", v2: "bent", v3: "bent", translate: "згинатися"},
    {id: 11, v1: "bet", v2: "bet", v3: "bet / betted", translate: "ставити"}, 
    {id: 12, v1: "bid", v2: "bid / bade", v3: "bid / bidden", translate: "ставити ставку"}, 
    {id: 13, v1: "bind", v2: "bound", v3: "bound", translate: "пов’язувати"}, 
    {id: 14, v1: "bite", v2: "bit", v3: "bitten", translate: "вкусити"}, 
    {id: 15, v1: "bleed", v2: "bled", v3: "bled", translate: "кровоточити"}, 
    {id: 16, v1: "blow", v2: "blew", v3: "blown", translate: "дути"}, 
    {id: 17, v1: "break", v2: "broke", v3: "broken", translate: "ламати"}, 
    {id: 18, v1: "breed", v2: "bred", v3: "bred", translate: "вирощувати"}, 
    {id: 19, v1: "bring", v2: "brought", v3: "brought", translate: "приносити"}, 
    {id: 20, v1: "broadcast", v2: "broadcast / broadcasted", v3: "broadcast / broadcasted", translate: "передавати"}, 
    {id: 21, v1: "browbeat", v2: "browbeat", v3: "browbeaten / browbeat", translate: "залякувати"}, 
    {id: 22, v1: "build", v2: "built", v3: "built", translate: "будувати"}, 
    {id: 23, v1: "burn", v2: "burnt / burned", v3: "burnt / burned", translate: "горіти"}, 
    {id: 24, v1: "burst", v2: "burst", v3: "burst", translate: "вибухати"}, 
    {id: 25, v1: "bust", v2: "bust / busted", v3: "bust / busted", translate: "розорювати"}, 
    {id: 26, v1: "buy", v2: "bought", v3: "bought", translate: "купляти"},  
    
    {id: 27, v1: "cast", v2: "cast", v3: "cast", translate: "кидати"}, 
    {id: 28, v1: "catch", v2: "caught", v3: "caught", translate: "хапати"}, 
    {id: 29, v1: "choose", v2: "chose", v3: "chosen", translate: "вибирати"}, 
    {id: 30, v1: "cling", v2: "clung", v3: "clung", translate: "вирощувати"}, 
    {id: 31, v1: "clothe", v2: "clad / clothed", v3: "clad / clothed", translate: "вирощувати"},
    {id: 32, v1: "come", v2: "cаme", v3: "come", translate: "приходити"}, 
    {id: 33, v1: "cost", v2: "cost", v3: "cost", translate: "коштувати"}, 
    {id: 34, v1: "creep", v2: "crept", v3: "crept", translate: "повзти"}, 
    {id: 35, v1: "crossbreed", v2: "crossbreed", v3: "crossbreed", translate: "схрещувати"}, 
    {id: 36, v1: "cut", v2: "cut", v3: "cut", translate: "різати"},

    {id: 37, v1: "daydream", v2: "daydreamt / daydreamed", v3: "daydreamt / daydreamed", translate: "мріяти"},
    {id: 38, v1: "dare", v2: "durst", v3: "dared", translate: "відважуватися"}, 
    {id: 39, v1: "deal", v2: "dealt", v3: "dealt", translate: "вирішувати"},
    {id: 40, v1: "dig", v2: "dug", v3: "dug", translate: "копати"},
    {id: 41, v1: "disprove", v2: "disproved", v3: "disproved / disproven", translate: "спростовувати"}, 
    {id: 42, v1: "dive", v2: "dove / dived", v3: "dived", translate: "ниряти"}, 
    {id: 43, v1: "do", v2: "did", v3: "done", translate: "робити"},
    {id: 44, v1: "draw", v2: "drew", v3: "drawn", translate: "малювати"}, 
    {id: 45, v1: "dream", v2: "dreamed / dreamt", v3: "dreamed / dreamt", translate: "мріяти"}, 
    {id: 46, v1: "drink", v2: "drank", v3: "drunk", translate: "пити"},
    {id: 47, v1: "drive", v2: "drove", v3: "driven", translate: "керувати"}, 
    {id: 48, v1: "dwell", v2: "dwelt / dwelled", v3: "dwelt / dwelled", translate: "жити"}, 

    {id: 49, v1: "eat", v2: "ate", v3: "eaten", translate: "їсти"}, 

    {id: 50, v1: "fall", v2: "fell", v3: "fallen", translate: "падати"},
    {id: 51, v1: "feed", v2: "fed", v3: "fed", translate: "годувати"}, 
    {id: 52, v1: "feel", v2: "felt", v3: "felt", translate: "відчувати"},
    {id: 53, v1: "fight", v2: "fought", v3: "fought", translate: "боротися"},
    {id: 54, v1: "find", v2: "found", v3: "found", translate: "знаходити"}, 
    {id: 55, v1: "fit", v2: "fit / fitted", v3: "fit / fitted", translate: "підходити"}, 
    {id: 56, v1: "flee", v2: "fled", v3: "fled", translate: "уникати"},
    {id: 57, v1: "fling", v2: "flung", v3: "flung", translate: "кидати"}, 
    {id: 58, v1: "fly", v2: "flew", v3: "flown", translate: "літати"}, 
    {id: 59, v1: "forbid", v2: "forbade", v3: "forbidden", translate: "забороняти"},
    {id: 60, v1: "forecast", v2: "forecast", v3: "forecast", translate: "передбачати"}, 
    {id: 61, v1: "forego / forgo", v2: "forewent", v3: "foregone", translate: "відмовлятися"},
    {id: 62, v1: "foresee", v2: "foresaw", v3: "foreseen", translate: "передбачати"},
    {id: 63, v1: "foretell", v2: "foretold", v3: "foretold", translate: "пророкувати"}, 
    {id: 64, v1: "forget", v2: "forgot", v3: "forgotten", translate: "забувати"}, 
    {id: 65, v1: "forgive", v2: "forgave", v3: "forgiven", translate: "пробачати"},
    {id: 66, v1: "forsake", v2: "forsook", v3: "forsaken", translate: "залишати"}, 
    {id: 67, v1: "freeze", v2: "froze", v3: "frozen", translate: "заморожувати"}, 
    {id: 68, v1: "frostbite", v2: "frostbit", v3: "frostbitten", translate: "відморожувати"}, 

    {id: 69, v1: "get", v2: "got", v3: "got / gotten", translate: "отримувати"}, 
    {id: 70, v1: "give", v2: "gave", v3: "given", translate: "давати"}, 
    {id: 71, v1: "go", v2: "went", v3: "gone", translate: "йти"}, 
    {id: 72, v1: "grind", v2: "ground", v3: "ground", translate: "молоти"}, 
    {id: 73, v1: "grow", v2: "grew", v3: "grown", translate: "рости"}, 

    {id: 74, v1: "hand-feed", v2: "hand-fed", v3: "hand-fed", translate: "годувати з рук"}, 
    {id: 75, v1: "handwrite", v2: "handwrote", v3: "handwritten", translate: "писати від руки"}, 
    {id: 76, v1: "hang", v2: "hung", v3: "hung", translate: "висіти"}, 
    {id: 77, v1: "have", v2: "had", v3: "had", translate: "мати (щось)"}, 
    {id: 78, v1: "hear", v2: "heard", v3: "heard", translate: "чути"}, 
    {id: 79, v1: "hew", v2: "hewed", v3: "hewn / hewed", translate: "рубати"}, 
    {id: 80, v1: "hide", v2: "hid", v3: "hidden", translate: "ховатися"}, 
    {id: 81, v1: "hit", v2: "hit", v3: "hit", translate: "вдаряти"}, 
    {id: 82, v1: "hold", v2: "held", v3: "held", translate: "тримати"}, 
    {id: 83, v1: "hurt", v2: "hurt", v3: "hurt", translate: "завдавати болю"}, 

    {id: 84, v1: "inbreed", v2: "inbred", v3: "inbred", translate: "розводити (рослини)"}, 
    {id: 85, v1: "inlay", v2: "inlaid", v3: "inlaid", translate: "інкрустовувати"}, 
    {id: 86, v1: "input", v2: "input / inputted", v3: "input / inputted", translate: "вводити дані"}, 
    {id: 87, v1: "interbreed", v2: "interbred", v3: "interbred", translate: "схрещувати"}, 
    {id: 88, v1: "interweave", v2: "interwove / interweaved", v3: "interwoven / interweaved", translate: "вплітати"}, 
    {id: 89, v1: "interwind", v2: "interwound", v3: "interwound", translate: "заплітати"}, 

    {id: 90, v1: "jerry-build", v2: "jerry-built", v3: "jerry-built", translate: "будувати халтурно"}, 

    {id: 91, v1: "keep", v2: "kept", v3: "kept", translate: "тримати"}, 
    {id: 92, v1: "kneel", v2: "knelt / kneeled", v3: "knelt / kneeled", translate: "ставати на коліна"}, 
    {id: 93, v1: "knit", v2: "knitted / knit", v3: "knitted / knit", translate: "в’язати"}, 
    {id: 94, v1: "know", v2: "knew", v3: "known", translate: "знати"},

    {id: 95, v1: "lay", v2: "laid", v3: "laid", translate: "класти (щось)"},
    {id: 96, v1: "lead", v2: "led", v3: "led", translate: "вести"},
    {id: 97, v1: "lean", v2: "leaned / leant", v3: "leaned / leant", translate: "спиратися"},
    {id: 98, v1: "leap", v2: "leaped / leapt", v3: "leaped / leapt", translate: "стрибати"},
    {id: 99, v1: "learn", v2: "learned / learnt", v3: "learned / learnt", translate: "вчити"},
    {id: 100, v1: "leave", v2: "left", v3: "left", translate: "полишати"},
    {id: 101, v1: "lend", v2: "lent", v3: "lent", translate: "давати у борг"},
    {id: 102, v1: "let", v2: "let", v3: "let", translate: "дозволяти"},
    {id: 103, v1: "lie", v2: "lay", v3: "lain", translate: "лежати"},
    {id: 104, v1: "light", v2: "lit / lighted", v3: "lit / lighted", translate: "освічувати"},
    {id: 105, v1: "lip-read", v2: "lip-read", v3: "lip-read", translate: "читати з губ"},
    {id: 106, v1: "lose", v2: "lost", v3: "lost", translate: "втрачати"},

    {id: 107, v1: "make", v2: "made", v3: "made", translate: "робити, створювати"},
    {id: 108, v1: "mean", v2: "meant", v3: "meant", translate: "означати"},
    {id: 109, v1: "meet", v2: "met", v3: "met", translate: "зустрічати"},
    {id: 110, v1: "miscast", v2: "miscast", v3: "miscast", translate: "неправильно вирахувати"},
    {id: 111, v1: "misdeal", v2: "misdealt", v3: "misdealt", translate: "діяти невірно"},
    {id: 112, v1: "misdo", v2: "misdid", v3: "misdone", translate: "помилятися"},
    {id: 113, v1: "misgive", v2: "misgave", v3: "misgiven", translate: "передчувати зле"},
    {id: 114, v1: "mishear", v2: "misheard", v3: "misheard", translate: "недочути"},
    {id: 115, v1: "mislead", v2: "misled", v3: "misled", translate: "вводити в оману"},
    {id: 116, v1: "mishit", v2: "mishit", v3: "mishit", translate: "промахнутися"},
    {id: 117, v1: "mislearn", v2: "mislearned / mislearnt", v3: "mislearned / mislearnt", translate: "вивчати невірно"},
    {id: 118, v1: "misread", v2: "misread", v3: "misread", translate: "неправильно тлумачити"},
    {id: 119, v1: "misset", v2: "misset", v3: "misset", translate: "невірно настроїти"},
    {id: 120, v1: "misspeak", v2: "misspoke", v3: "misspoken", translate: "обмовлятися"},
    {id: 121, v1: "misspell", v2: "misspelled / misspelt", v3: "misspelled / misspelt", translate: "писати з помилками"},
    {id: 122, v1: "misspend", v2: "misspent", v3: "misspent", translate: "розтринькувати гроші"},
    {id: 123, v1: "mistake", v2: "mistook", v3: "mistaken", translate: "помилятися"},
    {id: 124, v1: "misteach", v2: "mistaught", v3: "mistaught", translate: "вчити невірно"},
    {id: 125, v1: "misunderstand", v2: "misunderstood", v3: "misunderstood", translate: "не порозумітися"},
    {id: 126, v1: "miswrite", v2: "miswrote", v3: "miswritten", translate: "писати невірно"},
    {id: 127, v1: "mow", v2: "mowed", v3: "mowed / mown", translate: "жати"},

    {id: 128, v1: "offset", v2: "offset", v3: "offset", translate: "компенсовувати"},
    {id: 129, v1: "outbid", v2: "outbid", v3: "outbid", translate: "перекуповувати"},
    {id: 130, v1: "outbreed", v2: "outbred", v3: "outbred", translate: "виховувати поза сім’єю"},
    {id: 131, v1: "outdo", v2: "outdid", v3: "outdone", translate: "перевершувати"},
    {id: 132, v1: "outdraw", v2: "outdrew", v3: "outdrawn", translate: "привертати увагу"},
    {id: 133, v1: "outdrink", v2: "outdrank", v3: "outdrunk", translate: "перепити"},
    {id: 134, v1: "outdrive", v2: "outdrove", v3: "outdriven", translate: "обганяти"},
    {id: 135, v1: "outfight", v2: "outfought", v3: "outfought", translate: "перемагати в бою"},
    {id: 136, v1: "outfly", v2: "outflew", v3: "outflown", translate: "перелітати"},
    {id: 137, v1: "outgrow", v2: "outgrew", v3: "outgrown", translate: "переростати"},
    {id: 138, v1: "outleap", v2: "outleaped / outleapt", v3: "outleaped / outleapt", translate: "вистрибувати"},
    {id: 139, v1: "outride", v2: "outrode", v3: "outridden", translate: "випереджати"},
    {id: 140, v1: "outrun", v2: "outran", v3: "outrun", translate: "випереджати"},
    {id: 141, v1: "outsell", v2: "outsold", v3: "outsold", translate: "продавати більше"},
    {id: 142, v1: "outshine", v2: "outshined / outshone", v3: "outshined / outshone", translate: "затьмарювати"},
    {id: 143, v1: "outshoot", v2: "outshot", v3: "outshot", translate: "стріляти далі"},
    {id: 144, v1: "outsing", v2: "outsang", v3: "outsung", translate: "співати краще"},
    {id: 145, v1: "outsit", v2: "outsat", v3: "outsat", translate: "засиджуватися"},
    {id: 146, v1: "outsleep", v2: "outslept", v3: "outslept", translate: "прогавити"},
    {id: 147, v1: "outsmell", v2: "outsmelled / outsmelt", v3: "outsmelled / outsmelt", translate: "винюхати"},
    {id: 148, v1: "outspeak", v2: "outspoke", v3: "outspoken", translate: "висловлюватися"},
    {id: 149, v1: "outspeed", v2: "outsped", v3: "outsped", translate: "переганяти"},
    {id: 150, v1: "outspend", v2: "outspent", v3: "outspent", translate: "витрачати більше"},
    {id: 151, v1: "outswear", v2: "outswore", v3: "outsworn", translate: "клястися більше"},
    {id: 152, v1: "outswim", v2: "outswam", v3: "outswum", translate: "перепливти когось"},
    {id: 153, v1: "outthink", v2: "outthought", v3: "outthought", translate: "перехитрити"},
    {id: 154, v1: "outthrow", v2: "outthrew", v3: "outthrown", translate: "викидати"},
    {id: 155, v1: "outwrite", v2: "outwrote", v3: "outwritten", translate: "писати краще"},
    {id: 156, v1: "overbid", v2: "overbid", v3: "overbid", translate: "перебивати ціну"},
    {id: 157, v1: "overbuild", v2: "overbuilt", v3: "overbuilt", translate: "будувати занадто багато"},
    {id: 158, v1: "overbuy", v2: "overbought", v3: "overbought", translate: "купувати у великій кількості"},
    {id: 159, v1: "overcome", v2: "overcame", v3: "overcome", translate: "подолати"},
    {id: 160, v1: "overeat", v2: "overate", v3: "overeaten", translate: "переїдати"},
    {id: 161, v1: "overfeed", v2: "overfed", v3: "overfed", translate: "перегодовувати"},
    {id: 162, v1: "overhang", v2: "overhung", v3: "overhung", translate: "випинатися"},
    {id: 163, v1: "overhear", v2: "overheard", v3: "overheard", translate: "підслуховувати"},
    {id: 164, v1: "overlay", v2: "overlaid", v3: "overlaid", translate: "перекривати"},
    {id: 165, v1: "overpay", v2: "overpaid", v3: "overpaid", translate: "переплачувати"},
    {id: 166, v1: "override", v2: "overrode", v3: "overridden", translate: "відкидати"},
    {id: 167, v1: "overrun", v2: "overrun", v3: "overrun", translate: "виминати"},
    {id: 168, v1: "oversee", v2: "oversaw", v3: "overseen", translate: "спостерігати"},
    {id: 169, v1: "oversell", v2: "oversold", v3: "oversold", translate: "робити розпродаж"},
    {id: 170, v1: "oversew", v2: "oversewed", v3: "oversewn / oversewed", translate: "зшивати"},
    {id: 171, v1: "overshoot", v2: "overshot", v3: "overshot", translate: "промахуватися"},
    {id: 172, v1: "oversleep", v2: "overslept", v3: "overslept", translate: "проспати"},
    {id: 173, v1: "overspeak", v2: "overspoke", v3: "overspoken", translate: "багато говорити"},
    {id: 174, v1: "overspend", v2: "overspent", v3: "overspent", translate: "смітити грошима"},
    {id: 175, v1: "overtake", v2: "overtook", v3: "overtaken", translate: "доганяти"},
    {id: 176, v1: "overthink", v2: "overthought", v3: "overthought", translate: "мудрувати"},
    {id: 177, v1: "overthrow", v2: "overthrew", v3: "overthrown", translate: "скидати"},
    {id: 178, v1: "overwind", v2: "overwound", v3: "overwound", translate: "перекручувати"},
    {id: 179, v1: "overwrite", v2: "overwrote", v3: "overwritten", translate: "переписувати"},

    {id: 180, v1: "partake", v2: "partook", v3: "partaken", translate: "брати участь"},
    {id: 181, v1: "pay", v2: "paid", v3: "paid", translate: "платити"},
    {id: 182, v1: "plead", v2: "pleaded / pled", v3: "pleaded / pled", translate: "благати"},
    {id: 183, v1: "preset", v2: "preset", v3: "preset", translate: "заздалегідь встановлений"},
    {id: 184, v1: "proofread", v2: "proofread", v3: "proofread", translate: "коректувати"},
    {id: 185, v1: "prove", v2: "proved", v3: "proven / proved", translate: "доводити"},
    {id: 186, v1: "put", v2: "put", v3: "put", translate: "класти"},

    {id: 187, v1: "quick-freeze", v2: "quick-froze", v3: "quick-frozen", translate: "швидко заморожувати"},
    {id: 188, v1: "quit", v2: "quit", v3: "quit", translate: "виходити"},

    {id: 189, v1: "read", v2: "read", v3: "read", translate: "читати"},
    {id: 190, v1: "relay", v2: "relaid", v3: "relaid", translate: "змінювати"},
    {id: 191, v1: "remake", v2: "remade", v3: "remade", translate: "перероблювати"},
    {id: 192, v1: "repay", v2: "repaid", v3: "repaid", translate: "віддячувати"},
    {id: 193, v1: "resell", v2: "resold", v3: "resold", translate: "перепродавати"},
    {id: 194, v1: "reset", v2: "reset", v3: "reset", translate: "перезавантажувати"},
    {id: 195, v1: "retell", v2: "retold", v3: "retold", translate: "переказувати"},
    {id: 196, v1: "rewind", v2: "rewound", v3: "rewound", translate: "перемотувати"},
    {id: 197, v1: "rid", v2: "rid", v3: "rid", translate: "позбавлятися"},
    {id: 198, v1: "ride", v2: "rode", v3: "ridden", translate: "їхати"},
    {id: 199, v1: "ring", v2: "rang", v3: "rung", translate: "дзвонити"},
    {id: 200, v1: "rise", v2: "rose", v3: "risen", translate: "підніматись"},
    {id: 201, v1: "roughcast", v2: "roughcast", v3: "roughcast", translate: "намічати"},
    {id: 202, v1: "run", v2: "ran", v3: "run", translate: "бігти"},

]